//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.BM_Produce_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductModel", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data.Produc" +
        "e.XClasses")]
    [System.SerializableAttribute()]
    public partial class ProductModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Product_Breed_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_Breed_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Product_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_Harvester_BarkodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_Harvester_FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Product_Harvester_PersonPost_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Product_IsCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> Product_ParentProduct_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_Row_BarkodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Product_Row_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_User_BarkodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_User_FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Product_User_PersonPost_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Product_Breed_Id {
            get {
                return this.Product_Breed_IdField;
            }
            set {
                if ((this.Product_Breed_IdField.Equals(value) != true)) {
                    this.Product_Breed_IdField = value;
                    this.RaisePropertyChanged("Product_Breed_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Breed_Name {
            get {
                return this.Product_Breed_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_Breed_NameField, value) != true)) {
                    this.Product_Breed_NameField = value;
                    this.RaisePropertyChanged("Product_Breed_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Product_DateTime {
            get {
                return this.Product_DateTimeField;
            }
            set {
                if ((this.Product_DateTimeField.Equals(value) != true)) {
                    this.Product_DateTimeField = value;
                    this.RaisePropertyChanged("Product_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Error {
            get {
                return this.Product_ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_ErrorField, value) != true)) {
                    this.Product_ErrorField = value;
                    this.RaisePropertyChanged("Product_Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Harvester_Barkode {
            get {
                return this.Product_Harvester_BarkodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_Harvester_BarkodeField, value) != true)) {
                    this.Product_Harvester_BarkodeField = value;
                    this.RaisePropertyChanged("Product_Harvester_Barkode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Harvester_FullName {
            get {
                return this.Product_Harvester_FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_Harvester_FullNameField, value) != true)) {
                    this.Product_Harvester_FullNameField = value;
                    this.RaisePropertyChanged("Product_Harvester_FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Product_Harvester_PersonPost_Id {
            get {
                return this.Product_Harvester_PersonPost_IdField;
            }
            set {
                if ((this.Product_Harvester_PersonPost_IdField.Equals(value) != true)) {
                    this.Product_Harvester_PersonPost_IdField = value;
                    this.RaisePropertyChanged("Product_Harvester_PersonPost_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Product_IsComplete {
            get {
                return this.Product_IsCompleteField;
            }
            set {
                if ((this.Product_IsCompleteField.Equals(value) != true)) {
                    this.Product_IsCompleteField = value;
                    this.RaisePropertyChanged("Product_IsComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Product_ParentProduct_Id {
            get {
                return this.Product_ParentProduct_IdField;
            }
            set {
                if ((this.Product_ParentProduct_IdField.Equals(value) != true)) {
                    this.Product_ParentProduct_IdField = value;
                    this.RaisePropertyChanged("Product_ParentProduct_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Row_Barkode {
            get {
                return this.Product_Row_BarkodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_Row_BarkodeField, value) != true)) {
                    this.Product_Row_BarkodeField = value;
                    this.RaisePropertyChanged("Product_Row_Barkode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Product_Row_Id {
            get {
                return this.Product_Row_IdField;
            }
            set {
                if ((this.Product_Row_IdField.Equals(value) != true)) {
                    this.Product_Row_IdField = value;
                    this.RaisePropertyChanged("Product_Row_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_User_Barkode {
            get {
                return this.Product_User_BarkodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_User_BarkodeField, value) != true)) {
                    this.Product_User_BarkodeField = value;
                    this.RaisePropertyChanged("Product_User_Barkode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_User_FullName {
            get {
                return this.Product_User_FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_User_FullNameField, value) != true)) {
                    this.Product_User_FullNameField = value;
                    this.RaisePropertyChanged("Product_User_FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Product_User_PersonPost_Id {
            get {
                return this.Product_User_PersonPost_IdField;
            }
            set {
                if ((this.Product_User_PersonPost_IdField.Equals(value) != true)) {
                    this.Product_User_PersonPost_IdField = value;
                    this.RaisePropertyChanged("Product_User_PersonPost_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BM_Produce_ServiceReference.IBM_Produce_Service")]
    public interface IBM_Produce_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Produce_Service/DoWork", ReplyAction="http://tempuri.org/IBM_Produce_Service/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Produce_Service/DoWork", ReplyAction="http://tempuri.org/IBM_Produce_Service/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Produce_Service/GetProductModel", ReplyAction="http://tempuri.org/IBM_Produce_Service/GetProductModelResponse")]
        ServiceTest.BM_Produce_ServiceReference.GetProductModelResponse GetProductModel(ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Produce_Service/GetProductModel", ReplyAction="http://tempuri.org/IBM_Produce_Service/GetProductModelResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_Produce_ServiceReference.GetProductModelResponse> GetProductModelAsync(ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorMessage;
        
        public GetProductModelRequest() {
        }
        
        public GetProductModelRequest(string errorMessage) {
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProductModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_Produce_ServiceReference.ProductModel[] GetProductModelResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetProductModelResponse() {
        }
        
        public GetProductModelResponse(ServiceTest.BM_Produce_ServiceReference.ProductModel[] GetProductModelResult, string errorMessage) {
            this.GetProductModelResult = GetProductModelResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBM_Produce_ServiceChannel : ServiceTest.BM_Produce_ServiceReference.IBM_Produce_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BM_Produce_ServiceClient : System.ServiceModel.ClientBase<ServiceTest.BM_Produce_ServiceReference.IBM_Produce_Service>, ServiceTest.BM_Produce_ServiceReference.IBM_Produce_Service {
        
        public BM_Produce_ServiceClient() {
        }
        
        public BM_Produce_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BM_Produce_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_Produce_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_Produce_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_Produce_ServiceReference.GetProductModelResponse ServiceTest.BM_Produce_ServiceReference.IBM_Produce_Service.GetProductModel(ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest request) {
            return base.Channel.GetProductModel(request);
        }
        
        public ServiceTest.BM_Produce_ServiceReference.ProductModel[] GetProductModel(ref string errorMessage) {
            ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest inValue = new ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest();
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_Produce_ServiceReference.GetProductModelResponse retVal = ((ServiceTest.BM_Produce_ServiceReference.IBM_Produce_Service)(this)).GetProductModel(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.GetProductModelResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_Produce_ServiceReference.GetProductModelResponse> GetProductModelAsync(ServiceTest.BM_Produce_ServiceReference.GetProductModelRequest request) {
            return base.Channel.GetProductModelAsync(request);
        }
    }
}
