//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.BM_RS_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportWaybill", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class TransportWaybill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybill_Car_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybill_Car_Point_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybill_Company_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TransportWaybill_Destination_Point_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TransportWaybill_End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybill_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TransportWaybill_RS_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportWaybill_RS_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TransportWaybill_Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TransportWaybill_Start_Point_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransportWaybill_Type_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybill_Car_Id {
            get {
                return this.TransportWaybill_Car_IdField;
            }
            set {
                if ((this.TransportWaybill_Car_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Car_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Car_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybill_Car_Point_Id {
            get {
                return this.TransportWaybill_Car_Point_IdField;
            }
            set {
                if ((this.TransportWaybill_Car_Point_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Car_Point_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Car_Point_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybill_Company_Id {
            get {
                return this.TransportWaybill_Company_IdField;
            }
            set {
                if ((this.TransportWaybill_Company_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Company_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Company_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TransportWaybill_Destination_Point_Id {
            get {
                return this.TransportWaybill_Destination_Point_IdField;
            }
            set {
                if ((this.TransportWaybill_Destination_Point_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Destination_Point_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Destination_Point_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransportWaybill_End_DateTime {
            get {
                return this.TransportWaybill_End_DateTimeField;
            }
            set {
                if ((this.TransportWaybill_End_DateTimeField.Equals(value) != true)) {
                    this.TransportWaybill_End_DateTimeField = value;
                    this.RaisePropertyChanged("TransportWaybill_End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybill_Id {
            get {
                return this.TransportWaybill_IdField;
            }
            set {
                if ((this.TransportWaybill_IdField.Equals(value) != true)) {
                    this.TransportWaybill_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TransportWaybill_RS_Id {
            get {
                return this.TransportWaybill_RS_IdField;
            }
            set {
                if ((this.TransportWaybill_RS_IdField.Equals(value) != true)) {
                    this.TransportWaybill_RS_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_RS_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportWaybill_RS_Number {
            get {
                return this.TransportWaybill_RS_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportWaybill_RS_NumberField, value) != true)) {
                    this.TransportWaybill_RS_NumberField = value;
                    this.RaisePropertyChanged("TransportWaybill_RS_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransportWaybill_Start_DateTime {
            get {
                return this.TransportWaybill_Start_DateTimeField;
            }
            set {
                if ((this.TransportWaybill_Start_DateTimeField.Equals(value) != true)) {
                    this.TransportWaybill_Start_DateTimeField = value;
                    this.RaisePropertyChanged("TransportWaybill_Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TransportWaybill_Start_Point_Id {
            get {
                return this.TransportWaybill_Start_Point_IdField;
            }
            set {
                if ((this.TransportWaybill_Start_Point_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Start_Point_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Start_Point_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransportWaybill_Type_Id {
            get {
                return this.TransportWaybill_Type_IdField;
            }
            set {
                if ((this.TransportWaybill_Type_IdField.Equals(value) != true)) {
                    this.TransportWaybill_Type_IdField = value;
                    this.RaisePropertyChanged("TransportWaybill_Type_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportWaybillDetail", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class TransportWaybillDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportWaybillDetail_ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybillDetail_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportWaybillDetail_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransportWaybillDetail_ResultStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransportWaybillDetail_TransportWaybill_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportWaybillDetail_WaybillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransportWaybillDetail_WaybillStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TransportWaybillDetail__DateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportWaybillDetail_Error {
            get {
                return this.TransportWaybillDetail_ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportWaybillDetail_ErrorField, value) != true)) {
                    this.TransportWaybillDetail_ErrorField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybillDetail_Id {
            get {
                return this.TransportWaybillDetail_IdField;
            }
            set {
                if ((this.TransportWaybillDetail_IdField.Equals(value) != true)) {
                    this.TransportWaybillDetail_IdField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportWaybillDetail_Result {
            get {
                return this.TransportWaybillDetail_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportWaybillDetail_ResultField, value) != true)) {
                    this.TransportWaybillDetail_ResultField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransportWaybillDetail_ResultStatus {
            get {
                return this.TransportWaybillDetail_ResultStatusField;
            }
            set {
                if ((this.TransportWaybillDetail_ResultStatusField.Equals(value) != true)) {
                    this.TransportWaybillDetail_ResultStatusField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_ResultStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransportWaybillDetail_TransportWaybill_Id {
            get {
                return this.TransportWaybillDetail_TransportWaybill_IdField;
            }
            set {
                if ((this.TransportWaybillDetail_TransportWaybill_IdField.Equals(value) != true)) {
                    this.TransportWaybillDetail_TransportWaybill_IdField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_TransportWaybill_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportWaybillDetail_Waybill {
            get {
                return this.TransportWaybillDetail_WaybillField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportWaybillDetail_WaybillField, value) != true)) {
                    this.TransportWaybillDetail_WaybillField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_Waybill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransportWaybillDetail_WaybillStatus {
            get {
                return this.TransportWaybillDetail_WaybillStatusField;
            }
            set {
                if ((this.TransportWaybillDetail_WaybillStatusField.Equals(value) != true)) {
                    this.TransportWaybillDetail_WaybillStatusField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail_WaybillStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransportWaybillDetail__DateTime {
            get {
                return this.TransportWaybillDetail__DateTimeField;
            }
            set {
                if ((this.TransportWaybillDetail__DateTimeField.Equals(value) != true)) {
                    this.TransportWaybillDetail__DateTimeField = value;
                    this.RaisePropertyChanged("TransportWaybillDetail__DateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NonTransportWaybill", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class NonTransportWaybill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybill_CompanyBuyer_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybill_CompanySeler_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NonTransportWaybill_End_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybill_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> NonTransportWaybill_RS_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonTransportWaybill_RS_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NonTransportWaybill_Start_DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybill_TransportWaybill_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NonTransportWaybill_Type_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybill_CompanyBuyer_Id {
            get {
                return this.NonTransportWaybill_CompanyBuyer_IdField;
            }
            set {
                if ((this.NonTransportWaybill_CompanyBuyer_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_CompanyBuyer_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_CompanyBuyer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybill_CompanySeler_Id {
            get {
                return this.NonTransportWaybill_CompanySeler_IdField;
            }
            set {
                if ((this.NonTransportWaybill_CompanySeler_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_CompanySeler_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_CompanySeler_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NonTransportWaybill_End_DateTime {
            get {
                return this.NonTransportWaybill_End_DateTimeField;
            }
            set {
                if ((this.NonTransportWaybill_End_DateTimeField.Equals(value) != true)) {
                    this.NonTransportWaybill_End_DateTimeField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_End_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybill_Id {
            get {
                return this.NonTransportWaybill_IdField;
            }
            set {
                if ((this.NonTransportWaybill_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NonTransportWaybill_RS_Id {
            get {
                return this.NonTransportWaybill_RS_IdField;
            }
            set {
                if ((this.NonTransportWaybill_RS_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_RS_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_RS_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonTransportWaybill_RS_Number {
            get {
                return this.NonTransportWaybill_RS_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NonTransportWaybill_RS_NumberField, value) != true)) {
                    this.NonTransportWaybill_RS_NumberField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_RS_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NonTransportWaybill_Start_DateTime {
            get {
                return this.NonTransportWaybill_Start_DateTimeField;
            }
            set {
                if ((this.NonTransportWaybill_Start_DateTimeField.Equals(value) != true)) {
                    this.NonTransportWaybill_Start_DateTimeField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_Start_DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybill_TransportWaybill_Id {
            get {
                return this.NonTransportWaybill_TransportWaybill_IdField;
            }
            set {
                if ((this.NonTransportWaybill_TransportWaybill_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_TransportWaybill_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_TransportWaybill_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NonTransportWaybill_Type_Id {
            get {
                return this.NonTransportWaybill_Type_IdField;
            }
            set {
                if ((this.NonTransportWaybill_Type_IdField.Equals(value) != true)) {
                    this.NonTransportWaybill_Type_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybill_Type_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NonTransportWaybillDetail", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class NonTransportWaybillDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonTransportWaybillDetail_ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybillDetail_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NonTransportWaybillDetail_NonTransportWaybill_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonTransportWaybillDetail_ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NonTransportWaybillDetail_ResultStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NonTransportWaybillDetail_WaybillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NonTransportWaybillDetail_WaybillStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NonTransportWaybillDetail__DateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonTransportWaybillDetail_Error {
            get {
                return this.NonTransportWaybillDetail_ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.NonTransportWaybillDetail_ErrorField, value) != true)) {
                    this.NonTransportWaybillDetail_ErrorField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybillDetail_Id {
            get {
                return this.NonTransportWaybillDetail_IdField;
            }
            set {
                if ((this.NonTransportWaybillDetail_IdField.Equals(value) != true)) {
                    this.NonTransportWaybillDetail_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NonTransportWaybillDetail_NonTransportWaybill_Id {
            get {
                return this.NonTransportWaybillDetail_NonTransportWaybill_IdField;
            }
            set {
                if ((this.NonTransportWaybillDetail_NonTransportWaybill_IdField.Equals(value) != true)) {
                    this.NonTransportWaybillDetail_NonTransportWaybill_IdField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_NonTransportWaybill_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonTransportWaybillDetail_Result {
            get {
                return this.NonTransportWaybillDetail_ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.NonTransportWaybillDetail_ResultField, value) != true)) {
                    this.NonTransportWaybillDetail_ResultField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NonTransportWaybillDetail_ResultStatus {
            get {
                return this.NonTransportWaybillDetail_ResultStatusField;
            }
            set {
                if ((this.NonTransportWaybillDetail_ResultStatusField.Equals(value) != true)) {
                    this.NonTransportWaybillDetail_ResultStatusField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_ResultStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonTransportWaybillDetail_Waybill {
            get {
                return this.NonTransportWaybillDetail_WaybillField;
            }
            set {
                if ((object.ReferenceEquals(this.NonTransportWaybillDetail_WaybillField, value) != true)) {
                    this.NonTransportWaybillDetail_WaybillField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_Waybill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NonTransportWaybillDetail_WaybillStatus {
            get {
                return this.NonTransportWaybillDetail_WaybillStatusField;
            }
            set {
                if ((this.NonTransportWaybillDetail_WaybillStatusField.Equals(value) != true)) {
                    this.NonTransportWaybillDetail_WaybillStatusField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail_WaybillStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NonTransportWaybillDetail__DateTime {
            get {
                return this.NonTransportWaybillDetail__DateTimeField;
            }
            set {
                if ((this.NonTransportWaybillDetail__DateTimeField.Equals(value) != true)) {
                    this.NonTransportWaybillDetail__DateTimeField = value;
                    this.RaisePropertyChanged("NonTransportWaybillDetail__DateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BM_RS_ServiceReference.IBM_RS_Service")]
    public interface IBM_RS_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/GetTransportWaybills", ReplyAction="http://tempuri.org/IBM_RS_Service/GetTransportWaybillsResponse")]
        ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsResponse GetTransportWaybills(ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/GetTransportWaybills", ReplyAction="http://tempuri.org/IBM_RS_Service/GetTransportWaybillsResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsResponse> GetTransportWaybillsAsync(ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybill", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillResponse")]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillResponse InsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybill", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillResponse> InsertTransportWaybillAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillDetail", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillDetailResponse")]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailResponse InsertTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillDetail", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillDetailResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailResponse> InsertTransportWaybillDetailAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/NonInsertTransportWaybill", ReplyAction="http://tempuri.org/IBM_RS_Service/NonInsertTransportWaybillResponse")]
        ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillResponse NonInsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/NonInsertTransportWaybill", ReplyAction="http://tempuri.org/IBM_RS_Service/NonInsertTransportWaybillResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillResponse> NonInsertTransportWaybillAsync(ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertNonTransportWaybillDetail", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertNonTransportWaybillDetailResponse")]
        ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailResponse InsertNonTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertNonTransportWaybillDetail", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertNonTransportWaybillDetailResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailResponse> InsertNonTransportWaybillDetailAsync(ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillCompanyMove", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillCompanyMoveResponse")]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveResponse InsertTransportWaybillCompanyMove(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillCompanyMove", ReplyAction="http://tempuri.org/IBM_RS_Service/InsertTransportWaybillCompanyMoveResponse")]
        System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveResponse> InsertTransportWaybillCompanyMoveAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransportWaybills", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransportWaybillsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<long> id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<int> typeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<long> carPointId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<long> carId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Nullable<long> companyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Nullable<long> rSId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public bool rSIdFiltered;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string rSNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public bool rSNumberFiltered;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string errorMessage;
        
        public GetTransportWaybillsRequest() {
        }
        
        public GetTransportWaybillsRequest(System.Nullable<long> id, System.Nullable<int> typeId, System.Nullable<long> carPointId, System.Nullable<long> carId, System.Nullable<long> companyId, System.Nullable<long> rSId, bool rSIdFiltered, string rSNumber, bool rSNumberFiltered, string errorMessage) {
            this.id = id;
            this.typeId = typeId;
            this.carPointId = carPointId;
            this.carId = carId;
            this.companyId = companyId;
            this.rSId = rSId;
            this.rSIdFiltered = rSIdFiltered;
            this.rSNumber = rSNumber;
            this.rSNumberFiltered = rSNumberFiltered;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransportWaybillsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTransportWaybillsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.TransportWaybill[] GetTransportWaybillsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetTransportWaybillsResponse() {
        }
        
        public GetTransportWaybillsResponse(ServiceTest.BM_RS_ServiceReference.TransportWaybill[] GetTransportWaybillsResult, string errorMessage) {
            this.GetTransportWaybillsResult = GetTransportWaybillsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.TransportWaybill transportWaybill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillRequest() {
        }
        
        public InsertTransportWaybillRequest(ServiceTest.BM_RS_ServiceReference.TransportWaybill transportWaybill, string errorMessage) {
            this.transportWaybill = transportWaybill;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long InsertTransportWaybillResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillResponse() {
        }
        
        public InsertTransportWaybillResponse(long InsertTransportWaybillResult, string errorMessage) {
            this.InsertTransportWaybillResult = InsertTransportWaybillResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybillDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.TransportWaybillDetail transportWaybillDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillDetailRequest() {
        }
        
        public InsertTransportWaybillDetailRequest(ServiceTest.BM_RS_ServiceReference.TransportWaybillDetail transportWaybillDetail, string errorMessage) {
            this.transportWaybillDetail = transportWaybillDetail;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybillDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long InsertTransportWaybillDetailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillDetailResponse() {
        }
        
        public InsertTransportWaybillDetailResponse(long InsertTransportWaybillDetailResult, string errorMessage) {
            this.InsertTransportWaybillDetailResult = InsertTransportWaybillDetailResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NonInsertTransportWaybill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NonInsertTransportWaybillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.NonTransportWaybill nonTransportWaybill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public NonInsertTransportWaybillRequest() {
        }
        
        public NonInsertTransportWaybillRequest(ServiceTest.BM_RS_ServiceReference.NonTransportWaybill nonTransportWaybill, string errorMessage) {
            this.nonTransportWaybill = nonTransportWaybill;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NonInsertTransportWaybillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NonInsertTransportWaybillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long NonInsertTransportWaybillResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public NonInsertTransportWaybillResponse() {
        }
        
        public NonInsertTransportWaybillResponse(long NonInsertTransportWaybillResult, string errorMessage) {
            this.NonInsertTransportWaybillResult = NonInsertTransportWaybillResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertNonTransportWaybillDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertNonTransportWaybillDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.NonTransportWaybillDetail nonTransportWaybillDetail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertNonTransportWaybillDetailRequest() {
        }
        
        public InsertNonTransportWaybillDetailRequest(ServiceTest.BM_RS_ServiceReference.NonTransportWaybillDetail nonTransportWaybillDetail, string errorMessage) {
            this.nonTransportWaybillDetail = nonTransportWaybillDetail;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertNonTransportWaybillDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertNonTransportWaybillDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long InsertNonTransportWaybillDetailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertNonTransportWaybillDetailResponse() {
        }
        
        public InsertNonTransportWaybillDetailResponse(long InsertNonTransportWaybillDetailResult, string errorMessage) {
            this.InsertNonTransportWaybillDetailResult = InsertNonTransportWaybillDetailResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybillCompanyMove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillCompanyMoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string barCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillCompanyMoveRequest() {
        }
        
        public InsertTransportWaybillCompanyMoveRequest(string barCode, string errorMessage) {
            this.barCode = barCode;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTransportWaybillCompanyMoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertTransportWaybillCompanyMoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.BM_RS_ServiceReference.TransportWaybill InsertTransportWaybillCompanyMoveResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertTransportWaybillCompanyMoveResponse() {
        }
        
        public InsertTransportWaybillCompanyMoveResponse(ServiceTest.BM_RS_ServiceReference.TransportWaybill InsertTransportWaybillCompanyMoveResult, string errorMessage) {
            this.InsertTransportWaybillCompanyMoveResult = InsertTransportWaybillCompanyMoveResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBM_RS_ServiceChannel : ServiceTest.BM_RS_ServiceReference.IBM_RS_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BM_RS_ServiceClient : System.ServiceModel.ClientBase<ServiceTest.BM_RS_ServiceReference.IBM_RS_Service>, ServiceTest.BM_RS_ServiceReference.IBM_RS_Service {
        
        public BM_RS_ServiceClient() {
        }
        
        public BM_RS_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BM_RS_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_RS_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_RS_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.GetTransportWaybills(ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest request) {
            return base.Channel.GetTransportWaybills(request);
        }
        
        public ServiceTest.BM_RS_ServiceReference.TransportWaybill[] GetTransportWaybills(System.Nullable<long> id, System.Nullable<int> typeId, System.Nullable<long> carPointId, System.Nullable<long> carId, System.Nullable<long> companyId, System.Nullable<long> rSId, bool rSIdFiltered, string rSNumber, bool rSNumberFiltered, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest inValue = new ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest();
            inValue.id = id;
            inValue.typeId = typeId;
            inValue.carPointId = carPointId;
            inValue.carId = carId;
            inValue.companyId = companyId;
            inValue.rSId = rSId;
            inValue.rSIdFiltered = rSIdFiltered;
            inValue.rSNumber = rSNumber;
            inValue.rSNumberFiltered = rSNumberFiltered;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).GetTransportWaybills(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.GetTransportWaybillsResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsResponse> GetTransportWaybillsAsync(ServiceTest.BM_RS_ServiceReference.GetTransportWaybillsRequest request) {
            return base.Channel.GetTransportWaybillsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.InsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest request) {
            return base.Channel.InsertTransportWaybill(request);
        }
        
        public long InsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.TransportWaybill transportWaybill, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest inValue = new ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest();
            inValue.transportWaybill = transportWaybill;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).InsertTransportWaybill(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.InsertTransportWaybillResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillResponse> InsertTransportWaybillAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillRequest request) {
            return base.Channel.InsertTransportWaybillAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.InsertTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest request) {
            return base.Channel.InsertTransportWaybillDetail(request);
        }
        
        public long InsertTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.TransportWaybillDetail transportWaybillDetail, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest inValue = new ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest();
            inValue.transportWaybillDetail = transportWaybillDetail;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).InsertTransportWaybillDetail(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.InsertTransportWaybillDetailResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailResponse> InsertTransportWaybillDetailAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillDetailRequest request) {
            return base.Channel.InsertTransportWaybillDetailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.NonInsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest request) {
            return base.Channel.NonInsertTransportWaybill(request);
        }
        
        public long NonInsertTransportWaybill(ServiceTest.BM_RS_ServiceReference.NonTransportWaybill nonTransportWaybill, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest inValue = new ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest();
            inValue.nonTransportWaybill = nonTransportWaybill;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).NonInsertTransportWaybill(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.NonInsertTransportWaybillResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillResponse> NonInsertTransportWaybillAsync(ServiceTest.BM_RS_ServiceReference.NonInsertTransportWaybillRequest request) {
            return base.Channel.NonInsertTransportWaybillAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.InsertNonTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest request) {
            return base.Channel.InsertNonTransportWaybillDetail(request);
        }
        
        public long InsertNonTransportWaybillDetail(ServiceTest.BM_RS_ServiceReference.NonTransportWaybillDetail nonTransportWaybillDetail, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest inValue = new ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest();
            inValue.nonTransportWaybillDetail = nonTransportWaybillDetail;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).InsertNonTransportWaybillDetail(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.InsertNonTransportWaybillDetailResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailResponse> InsertNonTransportWaybillDetailAsync(ServiceTest.BM_RS_ServiceReference.InsertNonTransportWaybillDetailRequest request) {
            return base.Channel.InsertNonTransportWaybillDetailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveResponse ServiceTest.BM_RS_ServiceReference.IBM_RS_Service.InsertTransportWaybillCompanyMove(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest request) {
            return base.Channel.InsertTransportWaybillCompanyMove(request);
        }
        
        public ServiceTest.BM_RS_ServiceReference.TransportWaybill InsertTransportWaybillCompanyMove(string barCode, ref string errorMessage) {
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest inValue = new ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest();
            inValue.barCode = barCode;
            inValue.errorMessage = errorMessage;
            ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveResponse retVal = ((ServiceTest.BM_RS_ServiceReference.IBM_RS_Service)(this)).InsertTransportWaybillCompanyMove(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.InsertTransportWaybillCompanyMoveResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveResponse> InsertTransportWaybillCompanyMoveAsync(ServiceTest.BM_RS_ServiceReference.InsertTransportWaybillCompanyMoveRequest request) {
            return base.Channel.InsertTransportWaybillCompanyMoveAsync(request);
        }
    }
}
