//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BerryManagementAndroidApplication.ProduceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBM_Produce_Service", Namespace="http://tempuri.org/")]
    public partial class BM_Produce_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoWorkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductModelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBreedPropertyOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertBreedPropertiesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BM_Produce_Service() {
            this.Url = "http://localhost:8733/Design_Time_Addresses/BerryManagementWindowsService.WCF/BM_" +
                "Produce_Service/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoWorkCompletedEventHandler DoWorkCompleted;
        
        /// <remarks/>
        public event GetProductModelCompletedEventHandler GetProductModelCompleted;
        
        /// <remarks/>
        public event GetBreedPropertyCompletedEventHandler GetBreedPropertyCompleted;
        
        /// <remarks/>
        public event InsertBreedPropertiesCompletedEventHandler InsertBreedPropertiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBM_Produce_Service/DoWork", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DoWork() {
            this.Invoke("DoWork", new object[0]);
        }
        
        /// <remarks/>
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        /// <remarks/>
        public void DoWorkAsync(object userState) {
            if ((this.DoWorkOperationCompleted == null)) {
                this.DoWorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoWorkOperationCompleted);
            }
            this.InvokeAsync("DoWork", new object[0], this.DoWorkOperationCompleted, userState);
        }
        
        private void OnDoWorkOperationCompleted(object arg) {
            if ((this.DoWorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBM_Produce_Service/GetProductModel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data.Produc" +
            "e.XClasses")]
        public ProductModel[] GetProductModel([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string errorMessage) {
            object[] results = this.Invoke("GetProductModel", new object[] {
                        errorMessage});
            errorMessage = ((string)(results[1]));
            return ((ProductModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductModelAsync(string errorMessage) {
            this.GetProductModelAsync(errorMessage, null);
        }
        
        /// <remarks/>
        public void GetProductModelAsync(string errorMessage, object userState) {
            if ((this.GetProductModelOperationCompleted == null)) {
                this.GetProductModelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductModelOperationCompleted);
            }
            this.InvokeAsync("GetProductModel", new object[] {
                        errorMessage}, this.GetProductModelOperationCompleted, userState);
        }
        
        private void OnGetProductModelOperationCompleted(object arg) {
            if ((this.GetProductModelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductModelCompleted(this, new GetProductModelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBM_Produce_Service/GetBreedProperty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
        public BreedProperty[] GetBreedProperty([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> BreedPropertyId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool BreedPropertyIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> BreedId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool BreedIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> StartTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool StartTimeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> EndTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool EndTimeSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> SugarStart, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool SugarStartSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> SugarEnd, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool SugarEndSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<decimal> Density, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool DensitySpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string errorMessage) {
            object[] results = this.Invoke("GetBreedProperty", new object[] {
                        BreedPropertyId,
                        BreedPropertyIdSpecified,
                        BreedId,
                        BreedIdSpecified,
                        StartTime,
                        StartTimeSpecified,
                        EndTime,
                        EndTimeSpecified,
                        SugarStart,
                        SugarStartSpecified,
                        SugarEnd,
                        SugarEndSpecified,
                        Density,
                        DensitySpecified,
                        errorMessage});
            errorMessage = ((string)(results[1]));
            return ((BreedProperty[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBreedPropertyAsync(System.Nullable<long> BreedPropertyId, bool BreedPropertyIdSpecified, System.Nullable<long> BreedId, bool BreedIdSpecified, System.Nullable<System.DateTime> StartTime, bool StartTimeSpecified, System.Nullable<System.DateTime> EndTime, bool EndTimeSpecified, System.Nullable<decimal> SugarStart, bool SugarStartSpecified, System.Nullable<decimal> SugarEnd, bool SugarEndSpecified, System.Nullable<decimal> Density, bool DensitySpecified, string errorMessage) {
            this.GetBreedPropertyAsync(BreedPropertyId, BreedPropertyIdSpecified, BreedId, BreedIdSpecified, StartTime, StartTimeSpecified, EndTime, EndTimeSpecified, SugarStart, SugarStartSpecified, SugarEnd, SugarEndSpecified, Density, DensitySpecified, errorMessage, null);
        }
        
        /// <remarks/>
        public void GetBreedPropertyAsync(
                    System.Nullable<long> BreedPropertyId, 
                    bool BreedPropertyIdSpecified, 
                    System.Nullable<long> BreedId, 
                    bool BreedIdSpecified, 
                    System.Nullable<System.DateTime> StartTime, 
                    bool StartTimeSpecified, 
                    System.Nullable<System.DateTime> EndTime, 
                    bool EndTimeSpecified, 
                    System.Nullable<decimal> SugarStart, 
                    bool SugarStartSpecified, 
                    System.Nullable<decimal> SugarEnd, 
                    bool SugarEndSpecified, 
                    System.Nullable<decimal> Density, 
                    bool DensitySpecified, 
                    string errorMessage, 
                    object userState) {
            if ((this.GetBreedPropertyOperationCompleted == null)) {
                this.GetBreedPropertyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBreedPropertyOperationCompleted);
            }
            this.InvokeAsync("GetBreedProperty", new object[] {
                        BreedPropertyId,
                        BreedPropertyIdSpecified,
                        BreedId,
                        BreedIdSpecified,
                        StartTime,
                        StartTimeSpecified,
                        EndTime,
                        EndTimeSpecified,
                        SugarStart,
                        SugarStartSpecified,
                        SugarEnd,
                        SugarEndSpecified,
                        Density,
                        DensitySpecified,
                        errorMessage}, this.GetBreedPropertyOperationCompleted, userState);
        }
        
        private void OnGetBreedPropertyOperationCompleted(object arg) {
            if ((this.GetBreedPropertyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBreedPropertyCompleted(this, new GetBreedPropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBM_Produce_Service/InsertBreedProperties", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertBreedProperties([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BreedProperty breedProperty, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string errorMessage) {
            object[] results = this.Invoke("InsertBreedProperties", new object[] {
                        breedProperty,
                        errorMessage});
            errorMessage = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertBreedPropertiesAsync(BreedProperty breedProperty, string errorMessage) {
            this.InsertBreedPropertiesAsync(breedProperty, errorMessage, null);
        }
        
        /// <remarks/>
        public void InsertBreedPropertiesAsync(BreedProperty breedProperty, string errorMessage, object userState) {
            if ((this.InsertBreedPropertiesOperationCompleted == null)) {
                this.InsertBreedPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertBreedPropertiesOperationCompleted);
            }
            this.InvokeAsync("InsertBreedProperties", new object[] {
                        breedProperty,
                        errorMessage}, this.InsertBreedPropertiesOperationCompleted, userState);
        }
        
        private void OnInsertBreedPropertiesOperationCompleted(object arg) {
            if ((this.InsertBreedPropertiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertBreedPropertiesCompleted(this, new InsertBreedPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data.Produc" +
        "e.XClasses")]
    public partial class ProductModel {
        
        private long product_Breed_IdField;
        
        private bool product_Breed_IdFieldSpecified;
        
        private string product_Breed_NameField;
        
        private System.DateTime product_DateTimeField;
        
        private bool product_DateTimeFieldSpecified;
        
        private string product_ErrorField;
        
        private string product_Harvester_BarkodeField;
        
        private string product_Harvester_FullNameField;
        
        private long product_Harvester_PersonPost_IdField;
        
        private bool product_Harvester_PersonPost_IdFieldSpecified;
        
        private string product_IdField;
        
        private bool product_IsCompleteField;
        
        private bool product_IsCompleteFieldSpecified;
        
        private string product_ParentProduct_IdField;
        
        private string product_Row_BarkodeField;
        
        private long product_Row_IdField;
        
        private bool product_Row_IdFieldSpecified;
        
        private string product_User_BarkodeField;
        
        private string product_User_FullNameField;
        
        private long product_User_PersonPost_IdField;
        
        private bool product_User_PersonPost_IdFieldSpecified;
        
        /// <remarks/>
        public long Product_Breed_Id {
            get {
                return this.product_Breed_IdField;
            }
            set {
                this.product_Breed_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_Breed_IdSpecified {
            get {
                return this.product_Breed_IdFieldSpecified;
            }
            set {
                this.product_Breed_IdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Breed_Name {
            get {
                return this.product_Breed_NameField;
            }
            set {
                this.product_Breed_NameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Product_DateTime {
            get {
                return this.product_DateTimeField;
            }
            set {
                this.product_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_DateTimeSpecified {
            get {
                return this.product_DateTimeFieldSpecified;
            }
            set {
                this.product_DateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Error {
            get {
                return this.product_ErrorField;
            }
            set {
                this.product_ErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Harvester_Barkode {
            get {
                return this.product_Harvester_BarkodeField;
            }
            set {
                this.product_Harvester_BarkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Harvester_FullName {
            get {
                return this.product_Harvester_FullNameField;
            }
            set {
                this.product_Harvester_FullNameField = value;
            }
        }
        
        /// <remarks/>
        public long Product_Harvester_PersonPost_Id {
            get {
                return this.product_Harvester_PersonPost_IdField;
            }
            set {
                this.product_Harvester_PersonPost_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_Harvester_PersonPost_IdSpecified {
            get {
                return this.product_Harvester_PersonPost_IdFieldSpecified;
            }
            set {
                this.product_Harvester_PersonPost_IdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Product_Id {
            get {
                return this.product_IdField;
            }
            set {
                this.product_IdField = value;
            }
        }
        
        /// <remarks/>
        public bool Product_IsComplete {
            get {
                return this.product_IsCompleteField;
            }
            set {
                this.product_IsCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_IsCompleteSpecified {
            get {
                return this.product_IsCompleteFieldSpecified;
            }
            set {
                this.product_IsCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_ParentProduct_Id {
            get {
                return this.product_ParentProduct_IdField;
            }
            set {
                this.product_ParentProduct_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Row_Barkode {
            get {
                return this.product_Row_BarkodeField;
            }
            set {
                this.product_Row_BarkodeField = value;
            }
        }
        
        /// <remarks/>
        public long Product_Row_Id {
            get {
                return this.product_Row_IdField;
            }
            set {
                this.product_Row_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_Row_IdSpecified {
            get {
                return this.product_Row_IdFieldSpecified;
            }
            set {
                this.product_Row_IdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_User_Barkode {
            get {
                return this.product_User_BarkodeField;
            }
            set {
                this.product_User_BarkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_User_FullName {
            get {
                return this.product_User_FullNameField;
            }
            set {
                this.product_User_FullNameField = value;
            }
        }
        
        /// <remarks/>
        public long Product_User_PersonPost_Id {
            get {
                return this.product_User_PersonPost_IdField;
            }
            set {
                this.product_User_PersonPost_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Product_User_PersonPost_IdSpecified {
            get {
                return this.product_User_PersonPost_IdFieldSpecified;
            }
            set {
                this.product_User_PersonPost_IdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    public partial class BreedProperty {
        
        private System.Nullable<long> breedProperty_Breed_IdField;
        
        private bool breedProperty_Breed_IdFieldSpecified;
        
        private string breedProperty_Breed_NameField;
        
        private System.DateTime breedProperty_DateTimeField;
        
        private bool breedProperty_DateTimeFieldSpecified;
        
        private decimal breedProperty_DensityField;
        
        private bool breedProperty_DensityFieldSpecified;
        
        private long breedProperty_IdField;
        
        private bool breedProperty_IdFieldSpecified;
        
        private decimal breedProperty_SugarField;
        
        private bool breedProperty_SugarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> BreedProperty_Breed_Id {
            get {
                return this.breedProperty_Breed_IdField;
            }
            set {
                this.breedProperty_Breed_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreedProperty_Breed_IdSpecified {
            get {
                return this.breedProperty_Breed_IdFieldSpecified;
            }
            set {
                this.breedProperty_Breed_IdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BreedProperty_Breed_Name {
            get {
                return this.breedProperty_Breed_NameField;
            }
            set {
                this.breedProperty_Breed_NameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BreedProperty_DateTime {
            get {
                return this.breedProperty_DateTimeField;
            }
            set {
                this.breedProperty_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreedProperty_DateTimeSpecified {
            get {
                return this.breedProperty_DateTimeFieldSpecified;
            }
            set {
                this.breedProperty_DateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BreedProperty_Density {
            get {
                return this.breedProperty_DensityField;
            }
            set {
                this.breedProperty_DensityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreedProperty_DensitySpecified {
            get {
                return this.breedProperty_DensityFieldSpecified;
            }
            set {
                this.breedProperty_DensityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long BreedProperty_Id {
            get {
                return this.breedProperty_IdField;
            }
            set {
                this.breedProperty_IdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreedProperty_IdSpecified {
            get {
                return this.breedProperty_IdFieldSpecified;
            }
            set {
                this.breedProperty_IdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BreedProperty_Sugar {
            get {
                return this.breedProperty_SugarField;
            }
            set {
                this.breedProperty_SugarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BreedProperty_SugarSpecified {
            get {
                return this.breedProperty_SugarFieldSpecified;
            }
            set {
                this.breedProperty_SugarFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DoWorkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetProductModelCompletedEventHandler(object sender, GetProductModelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductModel[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBreedPropertyCompletedEventHandler(object sender, GetBreedPropertyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBreedPropertyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBreedPropertyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BreedProperty[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BreedProperty[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertBreedPropertiesCompletedEventHandler(object sender, InsertBreedPropertiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertBreedPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertBreedPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591