//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^XA\r\n^FT 225,60,0^A0N,40,50\r\n^FDBarcode^FS\r\n^FX Third section with barcode.\r\n^BY " +
            "2,260,180,\r\n^FO 215,80^BC\r\n^FDBarcode^FS\r\n^XZ")]
        public string RowLabelTemplate {
            get {
                return ((string)(this["RowLabelTemplate"]));
            }
            set {
                this["RowLabelTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^XA\r\n^FT 225,60,0^A0N,40,50\r\n^FDBarcode^FS\r\n^FX Third section with barcode.\r\n^BY " +
            "2,260,180,\r\n^FO 215,80^BC\r\n^FDBarcode^FS\r\n^XZ")]
        public string ContainerLabelTemplate {
            get {
                return ((string)(this["ContainerLabelTemplate"]));
            }
            set {
                this["ContainerLabelTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^XA\r\n^FT 225,60,0^A0N,40,50\r\n^FDPholder1^FS\r\n^FT 225,100,0^A0N,40,50\r\n^FDBarcode^" +
            "FS\r\n^FX Third section with barcode.\r\n^BY 2,260,150,\r\n^FO 215,110^BC\r\n^FDBarcode^" +
            "FS\r\n^XZ")]
        public string CarLabelTemplate {
            get {
                return ((string)(this["CarLabelTemplate"]));
            }
            set {
                this["CarLabelTemplate"] = value;
            }
        }
    }
}
