//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementApplication.BM_Template_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTemplateTitle", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class DocumentTemplateTitle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTemplateTitleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DocumentTemplateTitleDocumentTemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTemplateTitleExtensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTemplateTitleDescription {
            get {
                return this.DocumentTemplateTitleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTemplateTitleDescriptionField, value) != true)) {
                    this.DocumentTemplateTitleDescriptionField = value;
                    this.RaisePropertyChanged("DocumentTemplateTitleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DocumentTemplateTitleDocumentTemplateId {
            get {
                return this.DocumentTemplateTitleDocumentTemplateIdField;
            }
            set {
                if ((this.DocumentTemplateTitleDocumentTemplateIdField.Equals(value) != true)) {
                    this.DocumentTemplateTitleDocumentTemplateIdField = value;
                    this.RaisePropertyChanged("DocumentTemplateTitleDocumentTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTemplateTitleExtension {
            get {
                return this.DocumentTemplateTitleExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTemplateTitleExtensionField, value) != true)) {
                    this.DocumentTemplateTitleExtensionField = value;
                    this.RaisePropertyChanged("DocumentTemplateTitleExtension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTemplate", Namespace="http://schemas.datacontract.org/2004/07/BerryManagementWindowsService.Data")]
    [System.SerializableAttribute()]
    public partial class DocumentTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentTemplateDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DocumentTemplateIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentTemplateData {
            get {
                return this.DocumentTemplateDataField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTemplateDataField, value) != true)) {
                    this.DocumentTemplateDataField = value;
                    this.RaisePropertyChanged("DocumentTemplateData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DocumentTemplateId {
            get {
                return this.DocumentTemplateIdField;
            }
            set {
                if ((this.DocumentTemplateIdField.Equals(value) != true)) {
                    this.DocumentTemplateIdField = value;
                    this.RaisePropertyChanged("DocumentTemplateId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BM_Template_ServiceReference.IBM_Template_Service")]
    public interface IBM_Template_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateTitles", ReplyAction="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateTitlesResponse")]
        BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesResponse GetDocumentTemplateTitles(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateTitles", ReplyAction="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateTitlesResponse")]
        System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesResponse> GetDocumentTemplateTitlesAsync(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/GetDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateResponse")]
        BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateResponse GetDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/GetDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/GetDocumentTemplateResponse")]
        System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateResponse> GetDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/InsertDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/InsertDocumentTemplateResponse")]
        BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateResponse InsertDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/InsertDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/InsertDocumentTemplateResponse")]
        System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateResponse> InsertDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/UpdateDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/UpdateDocumentTemplateResponse")]
        BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateResponse UpdateDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/UpdateDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/UpdateDocumentTemplateResponse")]
        System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateResponse> UpdateDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/DeleteDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/DeleteDocumentTemplateResponse")]
        BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateResponse DeleteDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBM_Template_Service/DeleteDocumentTemplate", ReplyAction="http://tempuri.org/IBM_Template_Service/DeleteDocumentTemplateResponse")]
        System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateResponse> DeleteDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTemplateTitles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDocumentTemplateTitlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<long> documentTemplateTitleDocumentTemplateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetDocumentTemplateTitlesRequest() {
        }
        
        public GetDocumentTemplateTitlesRequest(System.Nullable<long> documentTemplateTitleDocumentTemplateId, string errorMessage) {
            this.documentTemplateTitleDocumentTemplateId = documentTemplateTitleDocumentTemplateId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTemplateTitlesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDocumentTemplateTitlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle> GetDocumentTemplateTitlesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetDocumentTemplateTitlesResponse() {
        }
        
        public GetDocumentTemplateTitlesResponse(System.Collections.Generic.List<BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle> GetDocumentTemplateTitlesResult, string errorMessage) {
            this.GetDocumentTemplateTitlesResult = GetDocumentTemplateTitlesResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDocumentTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long documentTemplateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetDocumentTemplateRequest() {
        }
        
        public GetDocumentTemplateRequest(long documentTemplateId, string errorMessage) {
            this.documentTemplateId = documentTemplateId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDocumentTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate GetDocumentTemplateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public GetDocumentTemplateResponse() {
        }
        
        public GetDocumentTemplateResponse(BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate GetDocumentTemplateResult, string errorMessage) {
            this.GetDocumentTemplateResult = GetDocumentTemplateResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDocumentTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDocumentTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorMessage;
        
        public InsertDocumentTemplateRequest() {
        }
        
        public InsertDocumentTemplateRequest(BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle, BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate, string errorMessage) {
            this.documentTemplateTitle = documentTemplateTitle;
            this.documentTemplate = documentTemplate;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDocumentTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDocumentTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long InsertDocumentTemplateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public InsertDocumentTemplateResponse() {
        }
        
        public InsertDocumentTemplateResponse(long InsertDocumentTemplateResult, string errorMessage) {
            this.InsertDocumentTemplateResult = InsertDocumentTemplateResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocumentTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDocumentTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorMessage;
        
        public UpdateDocumentTemplateRequest() {
        }
        
        public UpdateDocumentTemplateRequest(BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate, BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle, string errorMessage) {
            this.documentTemplate = documentTemplate;
            this.documentTemplateTitle = documentTemplateTitle;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocumentTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDocumentTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorMessage;
        
        public UpdateDocumentTemplateResponse() {
        }
        
        public UpdateDocumentTemplateResponse(string errorMessage) {
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDocumentTemplate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDocumentTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long documentTemplateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public DeleteDocumentTemplateRequest() {
        }
        
        public DeleteDocumentTemplateRequest(long documentTemplateId, string errorMessage) {
            this.documentTemplateId = documentTemplateId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDocumentTemplateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDocumentTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorMessage;
        
        public DeleteDocumentTemplateResponse() {
        }
        
        public DeleteDocumentTemplateResponse(string errorMessage) {
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBM_Template_ServiceChannel : BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BM_Template_ServiceClient : System.ServiceModel.ClientBase<BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service>, BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service {
        
        public BM_Template_ServiceClient() {
        }
        
        public BM_Template_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BM_Template_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_Template_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BM_Template_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesResponse BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service.GetDocumentTemplateTitles(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest request) {
            return base.Channel.GetDocumentTemplateTitles(request);
        }
        
        public System.Collections.Generic.List<BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle> GetDocumentTemplateTitles(System.Nullable<long> documentTemplateTitleDocumentTemplateId, ref string errorMessage) {
            BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest inValue = new BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest();
            inValue.documentTemplateTitleDocumentTemplateId = documentTemplateTitleDocumentTemplateId;
            inValue.errorMessage = errorMessage;
            BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesResponse retVal = ((BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service)(this)).GetDocumentTemplateTitles(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.GetDocumentTemplateTitlesResult;
        }
        
        public System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesResponse> GetDocumentTemplateTitlesAsync(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateTitlesRequest request) {
            return base.Channel.GetDocumentTemplateTitlesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateResponse BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service.GetDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest request) {
            return base.Channel.GetDocumentTemplate(request);
        }
        
        public BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate GetDocumentTemplate(long documentTemplateId, ref string errorMessage) {
            BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest inValue = new BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest();
            inValue.documentTemplateId = documentTemplateId;
            inValue.errorMessage = errorMessage;
            BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateResponse retVal = ((BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service)(this)).GetDocumentTemplate(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.GetDocumentTemplateResult;
        }
        
        public System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateResponse> GetDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.GetDocumentTemplateRequest request) {
            return base.Channel.GetDocumentTemplateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateResponse BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service.InsertDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest request) {
            return base.Channel.InsertDocumentTemplate(request);
        }
        
        public long InsertDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle, BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate, ref string errorMessage) {
            BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest inValue = new BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest();
            inValue.documentTemplateTitle = documentTemplateTitle;
            inValue.documentTemplate = documentTemplate;
            inValue.errorMessage = errorMessage;
            BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateResponse retVal = ((BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service)(this)).InsertDocumentTemplate(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.InsertDocumentTemplateResult;
        }
        
        public System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateResponse> InsertDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.InsertDocumentTemplateRequest request) {
            return base.Channel.InsertDocumentTemplateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateResponse BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service.UpdateDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest request) {
            return base.Channel.UpdateDocumentTemplate(request);
        }
        
        public void UpdateDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplate documentTemplate, BerryManagementApplication.BM_Template_ServiceReference.DocumentTemplateTitle documentTemplateTitle, ref string errorMessage) {
            BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest inValue = new BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest();
            inValue.documentTemplate = documentTemplate;
            inValue.documentTemplateTitle = documentTemplateTitle;
            inValue.errorMessage = errorMessage;
            BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateResponse retVal = ((BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service)(this)).UpdateDocumentTemplate(inValue);
            errorMessage = retVal.errorMessage;
        }
        
        public System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateResponse> UpdateDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.UpdateDocumentTemplateRequest request) {
            return base.Channel.UpdateDocumentTemplateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateResponse BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service.DeleteDocumentTemplate(BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest request) {
            return base.Channel.DeleteDocumentTemplate(request);
        }
        
        public void DeleteDocumentTemplate(long documentTemplateId, ref string errorMessage) {
            BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest inValue = new BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest();
            inValue.documentTemplateId = documentTemplateId;
            inValue.errorMessage = errorMessage;
            BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateResponse retVal = ((BerryManagementApplication.BM_Template_ServiceReference.IBM_Template_Service)(this)).DeleteDocumentTemplate(inValue);
            errorMessage = retVal.errorMessage;
        }
        
        public System.Threading.Tasks.Task<BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateResponse> DeleteDocumentTemplateAsync(BerryManagementApplication.BM_Template_ServiceReference.DeleteDocumentTemplateRequest request) {
            return base.Channel.DeleteDocumentTemplateAsync(request);
        }
    }
}
