//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BerryManagementEntities : DbContext
    {
        public BerryManagementEntities()
            : base("name=BerryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonDocument> PersonDocuments { get; set; }
        public virtual DbSet<PersonPostAgreement> PersonPostAgreements { get; set; }
        public virtual DbSet<PersonPost> PersonPosts { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Punishment> Punishments { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Breed> Breeds { get; set; }
        public virtual DbSet<Citizenship> Citizenships { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<LegalForm> LegalForms { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<ContainerMove> ContainerMoves { get; set; }
        public virtual DbSet<ContainerPack> ContainerPacks { get; set; }
        public virtual DbSet<ContainerWeight> ContainerWeights { get; set; }
        public virtual DbSet<HarvesterContainerDistribution> HarvesterContainerDistributions { get; set; }
        public virtual DbSet<HarvesterRowDistribution> HarvesterRowDistributions { get; set; }
        public virtual DbSet<OperationSetting> OperationSettings { get; set; }
        public virtual DbSet<ProductOwner> ProductOwners { get; set; }
        public virtual DbSet<ProductPack> ProductPacks { get; set; }
        public virtual DbSet<ProductQuality> ProductQualities { get; set; }
        public virtual DbSet<ProductReceive> ProductReceives { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<TakeRow> TakeRows { get; set; }
        public virtual DbSet<BreedProperty> BreedProperties { get; set; }
        public virtual DbSet<ContainerLocation> ContainerLocations { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<NonTransportWaybillDetail> NonTransportWaybillDetails { get; set; }
        public virtual DbSet<NonTransportWaybill> NonTransportWaybills { get; set; }
        public virtual DbSet<TransportWaybillDetail> TransportWaybillDetails { get; set; }
        public virtual DbSet<TransportWaybill> TransportWaybills { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PostRole> PostRoles { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Brigade> Brigades { get; set; }
        public virtual DbSet<CarDriver> CarDrivers { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CompanyCar> CompanyCars { get; set; }
        public virtual DbSet<Companye> Companyes { get; set; }
        public virtual DbSet<CompanyRow> CompanyRows { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<RowBreed> RowBreeds { get; set; }
        public virtual DbSet<Row> Rows { get; set; }
        public virtual DbSet<DocumentTemplate> DocumentTemplates { get; set; }
        public virtual DbSet<DocumentTemplateTitle> DocumentTemplateTitles { get; set; }
    
        [DbFunction("BerryManagementEntities", "tf_ContainerTypes")]
        public virtual IQueryable<tf_ContainerTypes_Result> tf_ContainerTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_ContainerTypes_Result>("[BerryManagementEntities].[tf_ContainerTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_EmployeeTypes")]
        public virtual IQueryable<tf_EmployeeTypes_Result> tf_EmployeeTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_EmployeeTypes_Result>("[BerryManagementEntities].[tf_EmployeeTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_GenderTypes")]
        public virtual IQueryable<tf_GenderTypes_Result> tf_GenderTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_GenderTypes_Result>("[BerryManagementEntities].[tf_GenderTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_GetBalanceSheetTypes")]
        public virtual IQueryable<tf_GetBalanceSheetTypes_Result> tf_GetBalanceSheetTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_GetBalanceSheetTypes_Result>("[BerryManagementEntities].[tf_GetBalanceSheetTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_HistoryOperationTypes")]
        public virtual IQueryable<tf_HistoryOperationTypes_Result> tf_HistoryOperationTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_HistoryOperationTypes_Result>("[BerryManagementEntities].[tf_HistoryOperationTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_LegalStatuseTypes")]
        public virtual IQueryable<tf_LegalStatuseTypes_Result> tf_LegalStatuseTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_LegalStatuseTypes_Result>("[BerryManagementEntities].[tf_LegalStatuseTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_MaritalStatus")]
        public virtual IQueryable<tf_MaritalStatus_Result> tf_MaritalStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_MaritalStatus_Result>("[BerryManagementEntities].[tf_MaritalStatus]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_OperationTypes")]
        public virtual IQueryable<tf_OperationTypes_Result> tf_OperationTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_OperationTypes_Result>("[BerryManagementEntities].[tf_OperationTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_PointTypes")]
        public virtual IQueryable<tf_PointTypes_Result> tf_PointTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_PointTypes_Result>("[BerryManagementEntities].[tf_PointTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_ProductQualityes")]
        public virtual IQueryable<tf_ProductQualityes_Result> tf_ProductQualityes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_ProductQualityes_Result>("[BerryManagementEntities].[tf_ProductQualityes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_PunishmentTypes")]
        public virtual IQueryable<tf_PunishmentTypes_Result> tf_PunishmentTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_PunishmentTypes_Result>("[BerryManagementEntities].[tf_PunishmentTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_SalaryTypes")]
        public virtual IQueryable<tf_SalaryTypes_Result> tf_SalaryTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_SalaryTypes_Result>("[BerryManagementEntities].[tf_SalaryTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_SideTypes")]
        public virtual IQueryable<tf_SideTypes_Result> tf_SideTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_SideTypes_Result>("[BerryManagementEntities].[tf_SideTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_UnitTypes")]
        public virtual IQueryable<tf_UnitTypes_Result> tf_UnitTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_UnitTypes_Result>("[BerryManagementEntities].[tf_UnitTypes]()");
        }
    
        [DbFunction("BerryManagementEntities", "tf_WaybillStates")]
        public virtual IQueryable<tf_WaybillStates_Result> tf_WaybillStates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tf_WaybillStates_Result>("[BerryManagementEntities].[tf_WaybillStates]()");
        }
    }
}
