//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreedProperty
    {
        public long BreedProperty_Id { get; set; }
        public System.DateTime BreedProperty_DateTime { get; set; }
        public Nullable<long> BreedProperty_Breed_Id { get; set; }
        public decimal BreedProperty_Sugar { get; set; }
        public decimal BreedProperty_Density { get; set; }
    }
}
