//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public long Car_Id { get; set; }
        public string Car_Number { get; set; }
        public string Car_Model { get; set; }
        public int Car_SideType_Id { get; set; }
    }
}
