//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDriver
    {
        public long CarDriver_Id { get; set; }
        public long CarDriver_Car_Id { get; set; }
        public long CarDriver_Person_Id { get; set; }
        public Nullable<long> CarDriver_PersonPost_Id { get; set; }
        public System.DateTime CarDriver_StartDate { get; set; }
        public Nullable<System.DateTime> CarDriver_EndDate { get; set; }
    }
}
