//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizenship
    {
        public long Citizenship_Id { get; set; }
        public string Citizenship_Name { get; set; }
        public string Citizenship_NameEn { get; set; }
    }
}
