//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRow
    {
        public long CompanyRow_Id { get; set; }
        public long CompanyRow_Company_Id { get; set; }
        public long CompanyRow_Row_Id { get; set; }
        public System.DateTime CompanyRow_StartDate { get; set; }
        public Nullable<System.DateTime> CompanyRow_EndDate { get; set; }
    }
}
