//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companye
    {
        public long Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Identity { get; set; }
        public int Company_SideType_Id { get; set; }
        public long Company_CitizenshipId { get; set; }
        public string Company_Address1 { get; set; }
        public string Company_Address2 { get; set; }
        public string Company_Phone1 { get; set; }
        public string Company_Phone2 { get; set; }
        public string Company_IBAN { get; set; }
        public string Company_RS_UserId { get; set; }
        public string Company_RS_Password { get; set; }
        public bool Company_IsResident { get; set; }
    }
}
