//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCar
    {
        public long CompanyCar_Id { get; set; }
        public long CompanyCar_Company_Id { get; set; }
        public long CompanyCar_Car_Id { get; set; }
        public System.DateTime CompanyCar_StartDate { get; set; }
        public Nullable<System.DateTime> CompanyCar_EndDate { get; set; }
    }
}
