//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerLocation
    {
        public long ContainerLocation_Id { get; set; }
        public string ContainerLocation_Container_BarCode { get; set; }
        public long ContainerLocation_Point_Id { get; set; }
        public System.Guid ContainerLocation_In_Id { get; set; }
        public long ContainerLocation_In_User_PersonPost_Id { get; set; }
        public System.DateTime ContainerLocation_In_DateTime { get; set; }
        public Nullable<System.Guid> ContainerLocation_Out_ContainerMoveInOut_Id { get; set; }
        public Nullable<long> ContainerLocation_Out_User_PersonPost_Id { get; set; }
        public Nullable<System.DateTime> ContainerLocation_Out_DateTime { get; set; }
    }
}
