//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerMove
    {
        public long ContainerMove_Id { get; set; }
        public long ContainerMove_TransportWaybill_Id { get; set; }
        public string ContainerMove_Container_BarCode { get; set; }
        public long ContainerMove_Car_Point_Id { get; set; }
        public System.Guid ContainerMove_In_ContainerMoveInOut_Id { get; set; }
        public long ContainerMove_In_User_PersonPost_Id { get; set; }
        public long ContainerMove_In_User_Point_Id { get; set; }
        public System.DateTime ContainerMove_In_DateTime { get; set; }
        public Nullable<System.Guid> ContainerMove_Out_ContainerMoveInOut_Id { get; set; }
        public Nullable<long> ContainerMove_Out_User_PersonPost_Id { get; set; }
        public Nullable<long> ContainerMove_Out_User_Point_Id { get; set; }
        public Nullable<System.DateTime> ContainerMove_Out_DateTime { get; set; }
    }
}
