//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerPack
    {
        public System.Guid ContainerPack_Id { get; set; }
        public string ContainerPack_Container_BarCode { get; set; }
        public string ContainerPack_Parent_Container_BarCode { get; set; }
        public System.DateTime ContainerPack_DateTime { get; set; }
        public long ContainerPack_User_PersonPost_Id { get; set; }
        public System.Guid ContainerPack_Parent_ContainerLocation_In_Id { get; set; }
        public bool ContainerPack_IsComplite { get; set; }
    }
}
