//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerWeight
    {
        public System.Guid ContainerWeight_Id { get; set; }
        public string ContainerWeight_Container_BarCode { get; set; }
        public decimal ContainerWeight_Net { get; set; }
        public decimal ContainerWeight_Gross { get; set; }
        public System.DateTime ContainerWeight_DateTime { get; set; }
        public long ContainerWeight_User_PersonPost_Id { get; set; }
    }
}
