//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTemplateTitle
    {
        public long DocumentTemplateTitleDocumentTemplateId { get; set; }
        public string DocumentTemplateTitleExtension { get; set; }
        public string DocumentTemplateTitleDescription { get; set; }
    }
}
