//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvesterRowDistribution
    {
        public long HarvesterRowDistribution_Id { get; set; }
        public long HarvesterRowDistribution_Row_Id { get; set; }
        public long HarvesterRowDistribution_Harvester_PersonPost_Id { get; set; }
        public System.Guid HarvesterRowDistribution_In_HarvesterRowDistributionInOut_Id { get; set; }
        public long HarvesterRowDistribution_In_User_PersonPost_Id { get; set; }
        public System.DateTime HarvesterRowDistribution_In_DateTime { get; set; }
        public Nullable<System.Guid> HarvesterRowDistribution_Out_HarvesterRowDistributionInOut_Id { get; set; }
        public Nullable<long> HarvesterRowDistribution_Out_User_PersonPost_Id { get; set; }
        public Nullable<System.DateTime> HarvesterRowDistribution_Out_DateTime { get; set; }
    }
}
