//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvesterContainerDistribution
    {
        public long HarvesterContainerDistribution_Id { get; set; }
        public string HarvesterContainerDistribution_Container_BarCode { get; set; }
        public long HarvesterContainerDistribution_Harvester_PersonPost_Id { get; set; }
        public System.Guid HarvesterContainerDistribution_In_HarvesterContainerDistributionInOut_Id { get; set; }
        public long HarvesterContainerDistribution_In_User_PersonPost_Id { get; set; }
        public System.DateTime HarvesterContainerDistribution_IN_DateTime { get; set; }
        public Nullable<System.Guid> HarvesterContainerDistribution_Out_HarvesterContainerDistributionInOut_Id { get; set; }
        public Nullable<long> HarvesterContainerDistribution_Out_User_PersonPost_Id { get; set; }
        public Nullable<System.DateTime> HarvesterContainerDistribution_Out_DateTime { get; set; }
    }
}
