//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonTransportWaybillDetail
    {
        public long NonTransportWaybillDetail_NonTransportWaybill_Id { get; set; }
        public string NonTransportWaybillDetail_Waybill { get; set; }
        public int NonTransportWaybillDetail_WaybillStatus { get; set; }
        public string NonTransportWaybillDetail_Error { get; set; }
        public Nullable<System.DateTime> NonTransportWaybillDetail_DateTime { get; set; }
        public int NonTransportWaybillDetail_State { get; set; }
    }
}
