//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonTransportWaybill
    {
        public long NonTransportWaybill_Id { get; set; }
        public int NonTransportWaybill_Type_Id { get; set; }
        public long NonTransportWaybill_TransportWaybill_Id { get; set; }
        public long NonTransportWaybill_CompanySeler_Id { get; set; }
        public long NonTransportWaybill_CompanyBuyer_Id { get; set; }
        public Nullable<long> NonTransportWaybill_RS_Id { get; set; }
        public string NonTransportWaybill_RS_Number { get; set; }
        public Nullable<System.DateTime> NonTransportWaybill_Start_DateTime { get; set; }
        public Nullable<System.DateTime> NonTransportWaybill_End_DateTime { get; set; }
    }
}
