//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPost
    {
        public long PersonPost_Id { get; set; }
        public string PersonPost_EmployeeBarCode { get; set; }
        public long PersonPost_BalanceSheetType_Id { get; set; }
        public long PersonPost_EmployeeType_Id { get; set; }
        public long PersonPost_Person_Id { get; set; }
        public long PersonPost_Post_Id { get; set; }
        public string PersonPost_Post_BarCodePrefix { get; set; }
        public Nullable<long> PersonPost_Brigade_Id { get; set; }
        public System.DateTime PersonPost_StartDate { get; set; }
        public Nullable<System.DateTime> PersonPost_EndDate { get; set; }
        public string PersonPost_DismissalOrder { get; set; }
        public string PersonPost_Description { get; set; }
    }
}
