//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDocument
    {
        public long PersonDocument_Id { get; set; }
        public long PersonDocument_Person_Id { get; set; }
        public long PersonDocument_DocumentType_Id { get; set; }
        public string PersonDocument_FirstName { get; set; }
        public string PersonDocument_LastName { get; set; }
        public System.DateTime PersonDocument_StartDate { get; set; }
        public Nullable<System.DateTime> PersonDocument_EndDate { get; set; }
        public string PersonDocument_Number { get; set; }
        public string PersonDocument_Isuer { get; set; }
        public long PersonDocument_Citizenship_Id { get; set; }
        public string PersonDocument_Description { get; set; }
    }
}
