//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long Person_Id { get; set; }
        public int Person_SideType_Id { get; set; }
        public Nullable<long> Person_Code { get; set; }
        public string Person_FirstName { get; set; }
        public string Person_LastName { get; set; }
        public string Person_Identity { get; set; }
        public Nullable<long> Person_LegalStatuseType_Id { get; set; }
        public Nullable<long> Person_LegalForm_Id { get; set; }
        public bool Person_IsResident { get; set; }
        public bool Person_GenderType_Id { get; set; }
        public System.DateTime Person_BirthDate { get; set; }
        public string Person_Address1 { get; set; }
        public string Person_Address2 { get; set; }
        public string Person_Phone1 { get; set; }
        public string Person_Phone2 { get; set; }
        public Nullable<long> Person_Bank_Id { get; set; }
        public string Person_BankAccount { get; set; }
        public string Person_BankClientName { get; set; }
        public string Person_MailAddress { get; set; }
        public Nullable<long> Person_MaritalStatus_Id { get; set; }
        public string Person_DrivingLicense { get; set; }
        public Nullable<long> Person_Nationality_Id { get; set; }
        public Nullable<long> Person_Citizenship_Id { get; set; }
        public string Person_Description { get; set; }
    }
}
