//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPostAgreement
    {
        public long PersonPostAgreement_Id { get; set; }
        public long PersonPostAgreement_PersonPost_Id { get; set; }
        public System.DateTime PersonPostAgreement_StartDate { get; set; }
        public Nullable<System.DateTime> PersonPostAgreement_EndDate { get; set; }
        public string PersonPostAgreement_Description { get; set; }
    }
}
