//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public long Point_Id { get; set; }
        public string Point_Name { get; set; }
        public bool Point_IsActive { get; set; }
        public string Point_PointType_Id { get; set; }
        public string Point_BarCode { get; set; }
        public Nullable<long> Point_Car_Id { get; set; }
        public string Point_Address { get; set; }
        public string Point_Description { get; set; }
    }
}
