//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostRole
    {
        public long PostRole_Id { get; set; }
        public long PostRole_Post_Id { get; set; }
        public long PostRole_Role_Id { get; set; }
        public System.DateTime PostRole_StartDate { get; set; }
        public Nullable<System.DateTime> PostRole_EndDate { get; set; }
    }
}
