//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long Post_Id { get; set; }
        public string Post_Name { get; set; }
        public string Post_Description { get; set; }
        public string Post_BarCodePrefix { get; set; }
        public long Post_BalanceSheetType_Id { get; set; }
    }
}
