//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOwner
    {
        public long ProductOwner_Id { get; set; }
        public System.Guid ProductOwner_Product_Id { get; set; }
        public long ProductOwner_CompanyId { get; set; }
        public System.DateTime ProducOwnert_DateTime { get; set; }
        public long ProductOwner_User_PersonPost_Id { get; set; }
        public int ProductOwner_Status { get; set; }
    }
}
