//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuality
    {
        public System.Guid ProductQuality_Id { get; set; }
        public System.Guid ProductQuality_Product_Id { get; set; }
        public long ProductQuality_Quality_Id { get; set; }
        public System.DateTime ProductQuality_DateTime { get; set; }
        public long ProductQuality_User_PersonPost_Id { get; set; }
    }
}
