//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid Product_Id { get; set; }
        public Nullable<System.Guid> Product_ParentProduct_Id { get; set; }
        public long Product_Row_Id { get; set; }
        public long Product_Harvester_PersonPost_Id { get; set; }
        public long Product_User_PersonPost_Id { get; set; }
        public System.DateTime Product_DateTime { get; set; }
        public long Product_Breed_Id { get; set; }
        public bool product_IsGood { get; set; }
    }
}
