//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPack
    {
        public long ProductPack_Id { get; set; }
        public System.Guid ProductPack_Product_Id { get; set; }
        public string ProductPack_Container_BarCode { get; set; }
        public System.Guid ProductPack_In_ProductPackInOut_Id { get; set; }
        public long ProductPack_In_User_PersonPost_Id { get; set; }
        public System.DateTime ProductPack_In_DateTime { get; set; }
        public Nullable<System.Guid> ProductPack_Out_ProductPackInOut_Id { get; set; }
        public Nullable<long> ProductPack_Out_User_PersonPost_Id { get; set; }
        public Nullable<System.DateTime> ProductPack_Out_DateTime { get; set; }
    }
}
