//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceive
    {
        public System.Guid ProductReceive_Id { get; set; }
        public System.Guid ProductReceive_Product_Id { get; set; }
        public string ProductReceive_HarvesterBarCode { get; set; }
        public string ProductReceive_ContainerBarCode { get; set; }
        public long ProductReceive_User_Point_Id { get; set; }
        public long ProductReceive_User_PersonPost_Id { get; set; }
        public System.DateTime ProductReceive_DateTime { get; set; }
        public bool ProductReceive_ProcessIsComplite { get; set; }
    }
}
