//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punishment
    {
        public System.Guid Punishment_Id { get; set; }
        public long Punishment_PunishmentType_Id { get; set; }
        public long Punishment_PersonPost_Id { get; set; }
        public System.DateTime Punishment_DateTime { get; set; }
        public long Punishment_User_PersonPost_Id { get; set; }
        public Nullable<long> Punishment_RecomenderUser_PersonPost_Id { get; set; }
        public string Punishment_Description { get; set; }
    }
}
