//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public long RolePermission_Id { get; set; }
        public long RolePermission_Role_Id { get; set; }
        public long RolePermission_Permission_Id { get; set; }
    }
}
