//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row
    {
        public long Row_Id { get; set; }
        public int Sector_Number { get; set; }
        public int Row_Number { get; set; }
        public string Row_Subrow_Number { get; set; }
        public string Row_Barkode { get; set; }
    }
}
