//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowBreed
    {
        public long RowBreed_Id { get; set; }
        public long RowBreed_Row_Id { get; set; }
        public long RowBreed_Breed_Id { get; set; }
        public int RowBreed_TreeCount { get; set; }
        public int RowBreed_PlantYear { get; set; }
        public System.DateTime RowBreed_StartDate { get; set; }
        public Nullable<System.DateTime> RowBreed_EndDate { get; set; }
    }
}
