//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.Guid Sale_Id { get; set; }
        public string Sale_Container_BarCode { get; set; }
        public System.DateTime Sale_DateTime { get; set; }
        public long Sale_User_PersonPost_Id { get; set; }
        public long Sale_Company_Id { get; set; }
        public System.Guid Sale_Identifier { get; set; }
        public bool Sale_IsComplite { get; set; }
    }
}
