//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeRow
    {
        public long TakeRow_Id { get; set; }
        public long TakeRow_Row_Id { get; set; }
        public Nullable<long> TakeRow_Brigade_Id { get; set; }
        public System.Guid TakeRow_In_TakeRowInOut_Id { get; set; }
        public long TakeRow_In_TUser_PersonPost_Id { get; set; }
        public System.DateTime TakeRow_In_DateTime { get; set; }
        public Nullable<System.Guid> TakeRow_Out_TakeRowInOut_Id { get; set; }
        public Nullable<long> TakeRow_Out_User_PersonPost_Id { get; set; }
        public Nullable<System.DateTime> TakeRow_Out_DateTime { get; set; }
    }
}
