//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportWaybill
    {
        public long TransportWaybill_Id { get; set; }
        public int TransportWaybill_Type_Id { get; set; }
        public long TransportWaybill_Car_Point_Id { get; set; }
        public long TransportWaybill_Car_Id { get; set; }
        public long TransportWaybill_Company_Id { get; set; }
        public Nullable<long> TransportWaybill_Start_Point_Id { get; set; }
        public Nullable<long> TransportWaybill_Destination_Point_Id { get; set; }
        public Nullable<long> TransportWaybill_RS_Id { get; set; }
        public string TransportWaybill_RS_Number { get; set; }
        public Nullable<System.DateTime> TransportWaybill_Start_DateTime { get; set; }
        public Nullable<System.DateTime> TransportWaybill_End_DateTime { get; set; }
    }
}
