//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportWaybillDetail
    {
        public long TransportWaybillDetail_TransportWaybill_Id { get; set; }
        public string TransportWaybillDetail_Waybill { get; set; }
        public int TransportWaybillDetail_WaybillStatus { get; set; }
        public string TransportWaybillDetail_Error { get; set; }
        public Nullable<System.DateTime> TransportWaybillDetail_DateTime { get; set; }
        public int TransportWaybillDetail_State { get; set; }
    }
}
