//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryManagementWindowsService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long User_Person_Id { get; set; }
        public string User_Password { get; set; }
        public bool User_PasswordIsReset { get; set; }
    }
}
