//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryPackagingApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\Projects\\BerryManagementSolution.v1.0\\BerryPackagingApplication\\bi" +
            "n\\Debug\\ContainersDB.sdf")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContainersDB.sdf")]
        public string DataBaseName {
            get {
                return ((string)(this["DataBaseName"]));
            }
            set {
                this["DataBaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int UseByDays {
            get {
                return ((int)(this["UseByDays"]));
            }
            set {
                this["UseByDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPrinterName {
            get {
                return ((string)(this["DefaultPrinterName"]));
            }
            set {
                this["DefaultPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                  ^XA\r\n                  ^FX LEFT SIDE\r\n                  ^FT10" +
            ",24,0^A0N,22,22\r\n                  ^FDFRESH BLUEBERRY - Variety ^FS\r\n           " +
            "       ^FT10,43,0^A0N,20,25\r\n                  ^FDWeight Net ^FS\r\n              " +
            "    ^FT10,62,0^A0N,20,25\r\n                  ^FDWeight Gross ^FS\r\n               " +
            "   ^FT10,81,0^A0N,20,25\r\n                  ^FDHarvest^FS\r\n                  ^FT1" +
            "0,100,0^A0N,20,25\r\n                  ^FDPacking^FS\r\n                  ^FT10,119," +
            "0^A0N,20,25\r\n                  ^FDUse by^FS\r\n                  ^FT10,137,0^A0N,2" +
            "0,25\r\n                  ^FDStorage conditions: store in a cool,  ^FS\r\n          " +
            "        ^FT10,158,0^A0N,22,25\r\n                  ^FDhygienic and dry place^FS\r\n " +
            "                 ^FT10,179,0^A0N,20,25\r\n                  ^FDCountry of origin^F" +
            "S\r\n                  ^FX RIGHT SIDE\r\n                  ^FT440,24,1^A0N,20,25\r\n  " +
            "                ^FDPholder5 ^FS\r\n                  ^FT440,43,1^A0N,20,25\r\n      " +
            "            ^FDPholder3 kgs ^FS\r\n                  ^FT435,62,1^A0N,20,25\r\n      " +
            "            ^FDPholder4 kgs^FS\r\n                  ^FT435,81,1^A0N,20,25\r\n       " +
            "           ^FDPholder1^FS\r\n                  ^FT435,100,1^A0N,20,25\r\n           " +
            "       ^FDPholder2^FS\r\n                  ^FT435,119,1^A0N,20,25\r\n               " +
            "   ^FDPholder6^FS\r\n                  ^FT355,179,0^A0N,20,25\r\n                  ^" +
            "FDGeorgia^FS\r\n                  ^FX Third section with barcode.\r\n               " +
            "   ^BY 2,60,45,\r\n                  ^FO35,185^BC^FDBarcode^FS\r\n                  " +
            "^XZ\r\n                ")]
        public string ZPL {
            get {
                return ((string)(this["ZPL"]));
            }
            set {
                this["ZPL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PalleteZpl {
            get {
                return ((string)(this["PalleteZpl"]));
            }
            set {
                this["PalleteZpl"] = value;
            }
        }
    }
}
